### DISCUSSION TITLE
🙋‍♀️ How to support show Mathematics in Markdown?

### DISCUSSION THREAD

**Discussion by lucian1037** [wylu1037/wylu1037.github.io#2] [Q&A] [answered]
Mathematics in Markdown?

**Comment by wylu1037** [comment, marked as answer]
### You can follow the [docs](https://gohugo.io/content-management/mathematics/)

- Upgrade you hugo version, the minimum supported version is `v0.122.0`;
- Add config key in your `hugo.yaml` file as below: 
```yaml
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
params:
  math: true
```
- Create a partial template to load MathJax or KaTeX. 

**layouts/partials/math.html**
```html
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
<script>
  MathJax = {
    tex: {
      displayMath: [['\\[', '\\]'], ['$$', '$$']],  // block
      inlineMath: [['\\(', '\\)']]                  // inline
    }
  };
</script>
```
- set the math parameter to true in front matter. 

**content/math-examples.md**
```markdown
---
date: 2024-01-24T18:09:49-08:00
params:
  math: true
title: Math examples
---

This is an inline \(a^*=x-b^*\) equation.

These are block equations:

\[a^*=x-b^*\]

\[ a^*=x-b^* \]

\[
a^*=x-b^*
\]

These are block equations using alternate delimiters:

$$a^*=x-b^*$$

$$ a^*=x-b^* $$

$$
a^*=x-b^*
$$
```
